/**
 * fidelity/docs.ts — documentation is a CONSUMER of computed state, never an
 * authority for it.
 *
 * Two mechanisms prevent drift:
 *
 * 1. `generateMarkdown` — the volatile status tables are GENERATED from the
 *    canonical audit result. The committed docs/source-fidelity.md must be
 *    byte-for-byte identical to the regenerated output; any drift fails.
 *
 * 2. `checkDocumentationClaims` — hand-written prose in docs/*.md may not
 *    claim a stronger status for a registered scope than the audit computes.
 *    Claims are detected by scope aliases followed by strong status tokens
 *    (closed / complete / authoritative). Unregistered areas are legacy
 *    narrative and are not checked; registering a scope opts its prose in.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { FidelityAuditResult, ScopeDefinition, ScopeResult } from './types.js';
import { SCOPE_STATUS_RANK } from './types.js';

export const GENERATED_DOC_PATH = 'docs/source-fidelity.md';

// ---------------------------------------------------------------------------
// Generated canonical document
// ---------------------------------------------------------------------------

export function generateMarkdown(result: FidelityAuditResult): string {
  const { summary } = result;
  const lines: string[] = [];
  lines.push('<!-- GENERATED by `npm run audit:source-fidelity -- --write`. Do not hand-edit; regenerate. -->');
  lines.push('');
  lines.push('# Source-fidelity audit (canonical derived state)');
  lines.push('');
  lines.push(
    'This file is COMPUTED from the evidence graph (`src/rules/fidelity/`): source obligations →',
    'semantic classification → implementation consumers → independent proofs → status.',
    'No status here can be edited by hand; edit the evidence instead.',
  );
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Measure | Count |');
  lines.push('| --- | ---: |');
  lines.push(`| Relevant source obligations | ${summary.totalObligations} |`);
  lines.push(`| Classified | ${summary.classified} |`);
  lines.push(`| Unclassified (blocks strong claims) | ${summary.unclassified} |`);
  lines.push(`| Deterministic obligations | ${summary.deterministicObligations} |`);
  lines.push(`| Deterministic with registered consumers | ${summary.implementedDeterministic} |`);
  lines.push(`| Deterministic lacking execution | ${summary.lackingExecution.length} |`);
  lines.push(`| Executable claims lacking required proof | ${summary.lackingRequiredProof.length} |`);
  lines.push(`| Unresolved source conflicts | ${summary.unresolvedConflicts.length} |`);
  lines.push(`| Explicitly table-facing | ${summary.tableFacing} |`);
  lines.push(`| Explicitly deferred/unsupported | ${summary.deferredUnsupported} |`);
  lines.push(`| Integrity violations | ${summary.integrityViolations.length} |`);
  lines.push('');
  lines.push('## Scope capability ladder');
  lines.push('');
  lines.push('Ladder: blocked < partial < executable < source-tested < replay-tested < closed.');
  lines.push('');
  lines.push('| Scope | Status | Obligations | Unclassified | Deterministic | Proven supported | Blockers |');
  lines.push('| --- | --- | ---: | ---: | ---: | ---: | --- |');
  for (const scope of result.scopes) {
    const blockers = scope.blockers.length > 0 ? scope.blockers.join('; ') : '—';
    lines.push(`| ${scope.title} (\`${scope.scopeId}\`) | ${scope.status} | ${scope.totalObligations} | ${scope.unclassified} | ${scope.deterministicExecutable} | ${scope.provenSupported} | ${blockers} |`);
  }
  lines.push('');

  const detailed = result.scopes.filter((scope) => scope.scopeId !== 'sourcebook-at-large');
  if (detailed.length > 0) {
    lines.push('## Scope detail');
    lines.push('');
    for (const scope of detailed) {
      appendScopeDetail(lines, scope);
    }
  }

  if (summary.lackingExecution.length > 0 && summary.lackingExecution.length <= 50) {
    lines.push('## Deterministic obligations without execution');
    lines.push('');
    for (const id of summary.lackingExecution) lines.push(`- ${id}`);
    lines.push('');
  } else if (summary.lackingExecution.length > 50) {
    lines.push(`## Deterministic obligations without execution`);
    lines.push('');
    lines.push(`${summary.lackingExecution.length} obligation(s); see the JSON audit output for the full list.`);
    lines.push('');
  }

  if (summary.integrityViolations.length > 0) {
    lines.push('## Integrity violations');
    lines.push('');
    for (const violation of summary.integrityViolations) {
      lines.push(`- **${violation.check}** — ${violation.detail}`);
    }
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

function appendScopeDetail(lines: string[], scope: ScopeResult): void {
  lines.push(`### ${scope.title} (\`${scope.scopeId}\`) — ${scope.status.toUpperCase()}`);
  lines.push('');
  if (scope.lackingRequiredProof.length > 0) {
    lines.push('Missing required proof:');
    lines.push('');
    for (const gap of scope.lackingRequiredProof) {
      lines.push(`- \`${gap.obligationId}\`: ${gap.missing.join(', ')}`);
    }
    lines.push('');
  }
  if (scope.unresolvedConflicts.length > 0) {
    lines.push(`Unadjudicated conflicts: ${scope.unresolvedConflicts.map((id) => `\`${id}\``).join(', ')}`);
    lines.push('');
  }
}

// ---------------------------------------------------------------------------
// Prose claim checking
// ---------------------------------------------------------------------------

const STRONG_STATUS_TOKENS = ['closed', 'complete', 'authoritative'] as const;

export interface DocumentationClaimViolation {
  file: string;
  line: number;
  detail: string;
}

/** Scan every `.md` file in `docsDir` (except the generated one) for claims
 * that a registered scope has a stronger status than the audit computes.
 * `scopes` are the scope DEFINITIONS from the world (they carry the prose
 * aliases the checker watches). */
export function checkDocumentationClaims(docsDir: string, result: FidelityAuditResult, scopes: readonly ScopeDefinition[], relativeFiles: readonly string[] = []): DocumentationClaimViolation[] {
  const violations: DocumentationClaimViolation[] = [];

  let files = relativeFiles;
  if (files.length === 0) {
    files = readdirSync(docsDir).filter((name) => name.endsWith('.md')).map((name) => name);
  }

  for (const fileName of files) {
    if (fileName === GENERATED_DOC_PATH.split('/').pop()) continue;
    let text: string;
    try {
      text = readFileSync(join(docsDir, fileName), 'utf8');
    } catch {
      continue;
    }
    const contentLines = text.split('\n');
    for (const scopeDef of scopes) {
      const scope = result.scopes.find(({ scopeId }) => scopeId === scopeDef.id);
      if (!scope) continue;
      for (const alias of [scopeDef.id, ...scopeDef.aliases]) {
        const pattern = new RegExp(`\\b${escapeRegExp(alias)}\\b[^\\n]{0,200}?\\b(${STRONG_STATUS_TOKENS.join('|')})\\b`, 'gi');
        contentLines.forEach((line, index) => {
          pattern.lastIndex = 0;
          let match: RegExpExecArray | null;
          while ((match = pattern.exec(line))) {
            const claimed = match[1].toLowerCase() as (typeof STRONG_STATUS_TOKENS)[number];
            const claimedRank = claimed === 'closed' ? SCOPE_STATUS_RANK.closed : claimed === 'complete' ? SCOPE_STATUS_RANK.closed : SCOPE_STATUS_RANK['source-tested'];
            if (claimedRank > SCOPE_STATUS_RANK[scope.status]) {
              violations.push({
                file: `docs/${fileName}`,
                line: index + 1,
                detail: `"${line.trim()}" claims ${claimed.toUpperCase()} for scope "${alias}" but the computed status is ${scope.status.toUpperCase()}${scope.blockers.length > 0 ? ` (blockers: ${scope.blockers.join('; ')})` : ''}`,
              });
            }
          }
        });
      }
    }
  }

  return violations;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** The generated document must match the canonical output byte-for-byte. */
export function checkGeneratedDocDrift(docsDir: string, result: FidelityAuditResult): DocumentationClaimViolation[] {
  const path = join(docsDir, GENERATED_DOC_PATH.split('/').pop()!);
  let committed: string | null = null;
  try {
    committed = readFileSync(path, 'utf8');
  } catch {
    return [{ file: GENERATED_DOC_PATH, line: 0, detail: 'generated canonical document is missing; run `npm run audit:source-fidelity -- --write`' }];
  }
  const regenerated = generateMarkdown(result);
  return committed === regenerated
    ? []
    : [{ file: GENERATED_DOC_PATH, line: 0, detail: 'docs/source-fidelity.md differs from the regenerated canonical audit output; run `npm run audit:source-fidelity -- --write`' }];
}
