/**
 * fidelity/docs.ts — documentation is a CONSUMER of computed state, never an
 * authority for it.
 *
 * `generateMarkdown` renders the canonical audit REPORT (computed by
 * strict.ts) into docs/source-fidelity.md; the committed file must be
 * byte-for-byte identical to the regenerated output or the audit fails.
 * Strong status labels here are COMPUTED, never asserted.
 *
 * Prose-claim policing lives in claims.ts (registry + secondary guard);
 * this module only renders and drift-checks generated state.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { FidelityAuditResult } from './types.js';

export const GENERATED_DOC_PATH = 'docs/source-fidelity.md';

/** The strict audit output the canonical document renders. */
export interface FidelityReport {
  result: FidelityAuditResult;
  unverifiedClaims: readonly { id: string; file: string; subject: string; strength: string; reason: string }[];
}

export function generateMarkdown(report: FidelityReport): string {
  const { summary } = report.result;
  const lines: string[] = [];
  lines.push('<!-- GENERATED by `npm run audit:source-fidelity -- --write`. Do not hand-edit; regenerate. -->');
  lines.push('');
  lines.push('# Source-fidelity audit (canonical derived state)');
  lines.push('');
  lines.push(
    'This file is COMPUTED from the evidence graph (`src/rules/fidelity/`): source obligations →',
    'semantic classification → implementation consumers → independent proofs → status.',
    'No status here can be edited by hand; edit the evidence instead.',
  );
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Measure | Count |');
  lines.push('| --- | ---: |');
  lines.push(`| Relevant source obligations | ${summary.totalObligations} |`);
  lines.push(`| Classified | ${summary.classified} |`);
  lines.push(`| Unclassified (blocks strong claims) | ${summary.unclassified} |`);
  lines.push(`| Deterministic obligations | ${summary.deterministicObligations} |`);
  lines.push(`| Deterministic with registered consumers | ${summary.implementedDeterministic} |`);
  lines.push(`| Deterministic lacking execution | ${summary.lackingExecution.length} |`);
  lines.push(`| Executable claims lacking required proof | ${summary.lackingRequiredProof.length} |`);
  lines.push(`| Unresolved source conflicts | ${summary.unresolvedConflicts.length} |`);
  lines.push(`| Explicitly table-facing | ${summary.tableFacing} |`);
  lines.push(`| Explicitly deferred/unsupported | ${summary.deferredUnsupported} |`);
  lines.push(`| Semantic contracts evaluated (executed evidence) | ${summary.evaluationsRun} |`);
  lines.push(`| Semantic evaluations passed | ${summary.evaluationsPassed} |`);
  lines.push(`| Semantic evaluations FAILED | ${summary.evaluationsFailed.length} |`);
  lines.push(`| Catalogued units fully decomposed | ${summary.unitsFullyDecomposed.length} |`);
  lines.push(`| Catalogued units partially decomposed | ${summary.unitsPartiallyDecomposed.length} |`);
  lines.push(`| Integrity violations | ${summary.integrityViolations.length} |`);
  lines.push('');
  lines.push('## Scope capability ladder');
  lines.push('');
  lines.push('Each rung adds exactly one mechanical predicate:');
  lines.push('');
  lines.push('- **blocked** — unclassified or unadjudicated-conflicted obligations present.');
  lines.push('- **partial** — no unknown material, but the frontier is incomplete or some deterministic obligation lacks full evidence.');
  lines.push('- **executable** — every deterministic obligation resolves to real code, carries machine-readable contract rows, and PASSED evaluation against them.');
  lines.push('- **source-tested** — executable + declared replay evidence for every stateful contract.');
  lines.push('- **replay-tested** — source-tested + required integration evidence.');
  lines.push('- **closed** — replay-tested + exhaustively accounted source frontier.');
  lines.push('');
  lines.push('| Scope | Status | Obligations | Unclassified | Deterministic | Proven supported | Frontier clauses (cov/irr/uncovered) | Blockers |');
  lines.push('| --- | --- | ---: | ---: | ---: | ---: | --- | --- |');
  for (const scope of report.result.scopes) {
    const blockers = scope.blockers.length > 0 ? scope.blockers.join('; ') : '—';
    const frontier = scope.frontierTotalClauses > 0 ? `${scope.frontierCoveredClauses}/${scope.frontierIrrelevantClauses}/${scope.frontierUncoveredIds.length}` : '—';
    lines.push(`| ${scope.title} (\`${scope.scopeId}\`) | ${scope.status} | ${scope.totalObligations} | ${scope.unclassified} | ${scope.deterministicExecutable} | ${scope.provenSupported} | ${frontier} | ${blockers} |`);
  }
  lines.push('');

  const detailed = report.result.scopes.filter((scope) => scope.scopeId !== 'sourcebook-at-large');
  if (detailed.length > 0) {
    lines.push('## Scope detail');
    lines.push('');
    for (const scope of detailed) {
      appendScopeDetail(lines, scope);
    }
  }

  if (summary.lackingExecution.length > 0 && summary.lackingExecution.length <= 50) {
    lines.push('## Deterministic obligations without execution');
    lines.push('');
    for (const id of summary.lackingExecution) lines.push(`- ${id}`);
    lines.push('');
  } else if (summary.lackingExecution.length > 50) {
    lines.push('## Deterministic obligations without execution');
    lines.push('');
    lines.push(`${summary.lackingExecution.length} obligation(s); see the JSON audit output for the full list.`);
    lines.push('');
  }

  if (report.unverifiedClaims.length > 0) {
    lines.push('## Project claims declared LEGACY / UNVERIFIED');
    lines.push('');
    lines.push('These strong project claims exist outside migrated fidelity scopes. They are reported, not silently accepted; migrating one means building its scope and rebinding the claim.');
    lines.push('');
    lines.push('| Claim | Document | Strength | Why unverified |');
    lines.push('| --- | --- | --- | --- |');
    for (const claim of report.unverifiedClaims) {
      lines.push(`| ${claim.subject} (\`${claim.id}\`) | ${claim.file} | ${claim.strength.toUpperCase()} | ${claim.reason} |`);
    }
    lines.push('');
  }

  if (summary.integrityViolations.length > 0) {
    lines.push('## Integrity violations');
    lines.push('');
    for (const violation of summary.integrityViolations) {
      lines.push(`- **${violation.check}** — ${violation.detail}`);
    }
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

function appendScopeDetail(lines: string[], scope: FidelityAuditResult['scopes'][number]): void {
  lines.push(`### ${scope.title} (\`${scope.scopeId}\`) — ${scope.status.toUpperCase()}`);
  lines.push('');
  if (scope.frontierTotalClauses > 0) {
    lines.push(
      `Source frontier: ${scope.frontierTotalClauses} clause(s) — ${scope.frontierCoveredClauses} covered by obligation passages,`
      + ` ${scope.frontierIrrelevantClauses} explicitly irrelevant, ${scope.frontierUncoveredIds.length} uncovered.`,
    );
    lines.push('');
  }
  if (scope.evaluatorFailures.length > 0) {
    lines.push('Semantic evaluation failures:');
    lines.push('');
    for (const failure of scope.evaluatorFailures) {
      lines.push(`- \`${failure.obligationId}\`: ${failure.failures} row(s) failed`);
    }
    lines.push('');
  }
  if (scope.lackingRequiredProof.length > 0) {
    lines.push('Missing required proof:');
    lines.push('');
    for (const gap of scope.lackingRequiredProof) {
      lines.push(`- \`${gap.obligationId}\`: ${gap.missing.join(', ')}`);
    }
    lines.push('');
  }
  if (scope.unresolvedConflicts.length > 0) {
    lines.push(`Unadjudicated conflicts: ${scope.unresolvedConflicts.map((id) => `\`${id}\``).join(', ')}`);
    lines.push('');
  }
}

/** The generated document must match the canonical output byte-for-byte. */
export function checkGeneratedDocDrift(docsDir: string, report: FidelityReport): { file: string; detail: string }[] {
  const path = join(docsDir, GENERATED_DOC_PATH.split('/').pop()!);
  let committed: string | null = null;
  try {
    committed = readFileSync(path, 'utf8');
  } catch {
    return [{ file: GENERATED_DOC_PATH, detail: 'generated canonical document is missing; run `npm run audit:source-fidelity -- --write`' }];
  }
  const regenerated = generateMarkdown(report);
  return committed === regenerated
    ? []
    : [{ file: GENERATED_DOC_PATH, detail: 'docs/source-fidelity.md differs from the regenerated canonical audit output; run `npm run audit:source-fidelity -- --write`' }];
}
