/**
 * fidelity/evaluate.ts — EXECUTES semantic contracts against production
 * implementations.
 *
 * The independence property:
 *
 *     contract rows (pure expectation DATA, hand-derived from source)
 *         vs
 *     adapter (maps row input → the real production implementation)
 *         ↓
 *     recorded ContractEvaluation (pass/fail per row)
 *
 * Expected values are written from the source semantics, never generated by
 * the implementation under test; adapters are the ONLY bridge to runtime code
 * and live one layer out (`adapters.ts`), so the evidence graph cannot import
 * its own way into agreement with the implementation. A proof may still cite
 * ordinary Vitest tests for traceability, but semantic proof is these
 * recorded results — static string presence in a test file is not enough for
 * strong status.
 *
 * Error rows: an adapter may return `{ error: string }` when the production
 * call throws; expected `{ error }` values compare against that message.
 */

import type {
  AdapterRegistry,
  ContractEvaluation,
  FidelityWorld,
  SemanticContract,
} from './types.js';

interface MutableEvaluationFailure {
  row: string;
  cls: ContractEvaluation['failures'][number]['cls'];
  expected: string;
  actual: string;
}

function normalizeActual(actual: unknown): unknown {
  if (
    typeof actual === 'object' && actual !== null &&
    'error' in actual && typeof (actual as { error: unknown }).error === 'string'
  ) {
    return { error: (actual as { error: string }).error };
  }
  return actual;
}

function deepEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (typeof a !== typeof b || a === null || b === null) return false;
  if (Array.isArray(a) || Array.isArray(b)) {
    if (!Array.isArray(a) || !Array.isArray(b) || a.length !== b.length) return false;
    return a.every((item, i) => deepEqual(item, b[i]));
  }
  if (typeof a === 'object') {
    const ka = Object.keys(a as object).sort();
    const kb = Object.keys(b as object).sort();
    if (!deepEqual(ka, kb)) return false;
    return ka.every((key) => deepEqual((a as Record<string, unknown>)[key], (b as Record<string, unknown>)[key]));
  }
  return false;
}

/** Evaluates one contract's rows through its adapter. Contracts without rows
 * yield no evaluation — they are declarative-only and can never reach strong
 * status; the engine treats them as unproven. */
export function evaluateContract(
  contract: SemanticContract,
  adapters: AdapterRegistry,
): ContractEvaluation | null {
  if (!contract.rows || contract.rows.length === 0) return null;
  const adapter = adapters.get(contract.obligationId);
  if (!adapter) {
    return {
      obligationId: contract.obligationId,
      adapterId: null,
      rowsRun: contract.rows.length,
      passed: false,
      failures: [{ row: '(adapter)', cls: 'positive', expected: 'a registered adapter', actual: 'none' }],
    };
  }
  const failures: MutableEvaluationFailure[] = [];
  for (const row of contract.rows) {
    let actual: unknown;
    try {
      actual = adapter.run(row.input);
    } catch (error) {
      actual = { error: error instanceof Error ? error.message : String(error) };
    }
    const normalized = normalizeActual(actual);
    if (!deepEqual(normalized, row.expected)) {
      failures.push({
        row: row.label,
        cls: row.cls,
        expected: JSON.stringify(row.expected),
        actual: JSON.stringify(normalized),
      });
    }
  }
  return {
    obligationId: contract.obligationId,
    adapterId: adapter.id,
    rowsRun: contract.rows.length,
    passed: failures.length === 0,
    failures,
  };
}

/** Evaluates every machine-readable contract in the world. */
export function evaluateContracts(world: FidelityWorld, adapters: AdapterRegistry): ContractEvaluation[] {
  return world.contracts
    .map((contract) => evaluateContract(contract, adapters))
    .filter((evaluation): evaluation is ContractEvaluation => evaluation !== null);
}
